-- ============================================================================
-- Stellar Dominion PHP rework — MySQL 8 schema
--
-- Port of shared/schema.ts (Drizzle ORM / PostgreSQL) to MySQL 8.
-- Translation notes:
--   varchar UUID PK gen_random_uuid()  -> CHAR(36) generated by the app
--   jsonb                             -> JSON
--   bigint({mode:'number'})           -> BIGINT
--   real                              -> DOUBLE
--   serial                            -> AUTO_INCREMENT
--   timestamp                         -> DATETIME
--
-- Run: mysql -u root -p < database/schema.sql
-- Or:  php database/migrate.php
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS users (
  id            CHAR(36)      NOT NULL PRIMARY KEY,
  username      VARCHAR(50)   NOT NULL UNIQUE,
  password_hash VARCHAR(255)  NOT NULL,
  email         VARCHAR(255)  NOT NULL UNIQUE,
  first_name    VARCHAR(100)  NULL,
  last_name     VARCHAR(100)  NULL,
  profile_image_url VARCHAR(500) NULL,
  last_login_at DATETIME      NULL,
  is_admin      TINYINT(1)    NOT NULL DEFAULT 0,
  created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sessions (
  sid     VARCHAR(128) NOT NULL PRIMARY KEY,
  sess    JSON         NULL,
  expire  DATETIME     NOT NULL,
  INDEX idx_sessions_expire (expire)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Core player state (mirrors player_states "mega table" — JSON columns)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player_states (
  id                 CHAR(36)  NOT NULL PRIMARY KEY,
  user_id            CHAR(36)  NOT NULL UNIQUE,
  -- Planet / universe
  setup_complete     TINYINT(1) NOT NULL DEFAULT 0,
  planet_name        VARCHAR(100) NOT NULL DEFAULT 'New Colony',
  coordinates        VARCHAR(32)  NOT NULL DEFAULT '[1:1:1]',
  known_planets      JSON       NULL,
  travel_state       JSON       NULL,
  travel_log         JSON       NULL,
  -- Resources
  resources          JSON       NOT NULL,
  last_resource_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Buildings & construction queue
  buildings          JSON       NOT NULL,
  orbital_buildings  JSON       NULL,
  cron_jobs          JSON       NULL,
  -- Research
  research           JSON       NOT NULL,
  research_queue     JSON       NULL,
  research_history   JSON       NULL,
  active_research    JSON       NULL,
  research_bonuses   JSON       NULL,
  research_lab       JSON       NULL,
  -- Turns
  turns_data         JSON       NULL,
  total_turns        INT        NOT NULL DEFAULT 0,
  current_turns      INT        NOT NULL DEFAULT 0,
  last_turn_update   DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Units / fleet
  units              JSON       NOT NULL,
  -- Empire progression
  empire_level       INT        NOT NULL DEFAULT 1,
  empire_experience  BIGINT     NOT NULL DEFAULT 0,
  tier               INT        NOT NULL DEFAULT 1,
  tier_experience    BIGINT     NOT NULL DEFAULT 0,
  prestige_level     INT        NOT NULL DEFAULT 0,
  prestige_bonus     JSON       NULL,
  -- OGame subsystems
  missile_silo       JSON       NULL,
  moons_data         JSON       NULL,
  terraformer        JSON       NULL,
  active_officers    JSON       NULL,
  -- Misc
  artifacts          JSON       NULL,
  ship_fittings      JSON       NULL,
  occupations        JSON       NULL,
  occupying          JSON       NULL,
  created_at         DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_profiles (
  id               CHAR(36) NOT NULL PRIMARY KEY,
  user_id          CHAR(36) NOT NULL UNIQUE,
  display_name     VARCHAR(100) NULL,
  bio              TEXT     NULL,
  level            INT      NOT NULL DEFAULT 1,
  total_experience BIGINT   NOT NULL DEFAULT 0,
  prestige_level   INT      NOT NULL DEFAULT 0,
  empire_power     BIGINT   NOT NULL DEFAULT 0,
  fleet_power      BIGINT   NOT NULL DEFAULT 0,
  attributes       JSON     NULL,
  categories       JSON     NULL,
  is_online        TINYINT(1) NOT NULL DEFAULT 0,
  last_activity_at DATETIME NULL,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_colonies (
  id            CHAR(36) NOT NULL PRIMARY KEY,
  player_id     CHAR(36) NOT NULL,
  planet_id     CHAR(36) NULL,
  colony_name   VARCHAR(100) NOT NULL DEFAULT 'Colony',
  colony_type   VARCHAR(50)  NOT NULL DEFAULT 'terrestrial',
  colony_level  INT      NOT NULL DEFAULT 1,
  population    INT      NOT NULL DEFAULT 1000,
  built_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_colonies_player FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Universe generation (shared/config/universeGenerationConfig.ts)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS universes (
  id         CHAR(36) NOT NULL PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  realm_id   VARCHAR(50)  NULL,
  seed       BIGINT  NOT NULL DEFAULT 1337,
  galaxy_count INT    NOT NULL DEFAULT 9,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS star_systems (
  id          CHAR(36) NOT NULL PRIMARY KEY,
  universe_id CHAR(36) NOT NULL,
  galaxy      INT NOT NULL DEFAULT 1,
  sector      INT NOT NULL DEFAULT 1,
  system      INT NOT NULL DEFAULT 1,
  name        VARCHAR(100) NULL,
  coordinates VARCHAR(32) NULL,
  owner_id    CHAR(36) NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_coords (universe_id, galaxy, sector, system),
  CONSTRAINT fk_systems_universe FOREIGN KEY (universe_id) REFERENCES universes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS planets (
  id           CHAR(36) NOT NULL PRIMARY KEY,
  system_id    CHAR(36) NOT NULL,
  name         VARCHAR(100) NOT NULL,
  planet_type  VARCHAR(50)  NOT NULL DEFAULT 'terrestrial',
  position     INT      NOT NULL DEFAULT 1,
  size         INT      NOT NULL DEFAULT 10000,
  temperature  INT      NOT NULL DEFAULT 0,
  owner_id     CHAR(36) NULL,
  metal_richness    DOUBLE NOT NULL DEFAULT 1.0,
  crystal_richness  DOUBLE NOT NULL DEFAULT 1.0,
  deuterium_richness DOUBLE NOT NULL DEFAULT 1.0,
  is_moon      TINYINT(1) NOT NULL DEFAULT 0,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_planets_system FOREIGN KEY (system_id) REFERENCES star_systems(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Fleets & missions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fleets (
  id         CHAR(36) NOT NULL PRIMARY KEY,
  owner_id   CHAR(36) NOT NULL,
  name       VARCHAR(100) NULL,
  ships      JSON NOT NULL,
  location   VARCHAR(32) NULL,
  destination VARCHAR(32) NULL,
  status     ENUM('idle','moving','combat','returning') NOT NULL DEFAULT 'idle',
  mission    ENUM('attack','transport','colonize','spy','defend','expedition') NULL,
  resources  JSON NULL,
  departure_time DATETIME NULL,
  arrival_time   DATETIME NULL,
  return_time    DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fleets_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS missions (
  id            CHAR(36) NOT NULL PRIMARY KEY,
  fleet_id      CHAR(36) NULL,
  user_id       CHAR(36) NOT NULL,
  type          ENUM('attack','transport','espionage','sabotage','colonize','defend','expedition') NOT NULL,
  status        ENUM('outbound','return','completed','failed') NOT NULL DEFAULT 'outbound',
  target        VARCHAR(32) NULL,
  origin        VARCHAR(32) NULL,
  units         JSON NULL,
  cargo         JSON NULL,
  departure_time DATETIME NULL,
  arrival_time   DATETIME NULL,
  return_time    DATETIME NULL,
  processed     TINYINT(1) NOT NULL DEFAULT 0,
  result        JSON NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_missions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Combat
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS battles (
  id              CHAR(36) NOT NULL PRIMARY KEY,
  attacker_id     CHAR(36) NULL,
  defender_id     CHAR(36) NULL,
  type            ENUM('raid','attack','spy','sabotage') NOT NULL DEFAULT 'attack',
  status          ENUM('pending','completed','failed') NOT NULL DEFAULT 'pending',
  attacker_coords VARCHAR(32) NULL,
  defender_coords VARCHAR(32) NULL,
  winner          ENUM('attacker','defender','draw','spy_success','spy_failed') NULL,
  attacker_fleet  JSON NULL,
  defender_fleet  JSON NULL,
  attacker_losses JSON NULL,
  defender_losses JSON NULL,
  loot            JSON NULL,
  debris          JSON NULL,
  rounds          INT NOT NULL DEFAULT 0,
  battle_log      JSON NULL,
  completed_at    DATETIME NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_battles_attacker FOREIGN KEY (attacker_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_battles_defender FOREIGN KEY (defender_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS battle_logs (
  id                    CHAR(36) NOT NULL PRIMARY KEY,
  battle_id             CHAR(36) NOT NULL,
  round                 INT NOT NULL DEFAULT 0,
  attacker_damage_dealt BIGINT NOT NULL DEFAULT 0,
  defender_damage_dealt BIGINT NOT NULL DEFAULT 0,
  units_destroyed       JSON NULL,
  log                   TEXT NULL,
  created_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_battlelogs_battle FOREIGN KEY (battle_id) REFERENCES battles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS combat_stats (
  id                 CHAR(36) NOT NULL PRIMARY KEY,
  player_id          CHAR(36) NOT NULL UNIQUE,
  total_battles      INT NOT NULL DEFAULT 0,
  wins               INT NOT NULL DEFAULT 0,
  losses             INT NOT NULL DEFAULT 0,
  draws              INT NOT NULL DEFAULT 0,
  units_destroyed    BIGINT NOT NULL DEFAULT 0,
  units_lost         BIGINT NOT NULL DEFAULT 0,
  combat_rating      INT NOT NULL DEFAULT 1000,
  raid_rating        INT NOT NULL DEFAULT 1000,
  updated_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_combatstats_player FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Research
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS research_technologies (
  id             CHAR(36) NOT NULL PRIMARY KEY,
  tech_key       VARCHAR(64) NOT NULL UNIQUE,
  name           VARCHAR(100) NOT NULL,
  branch         VARCHAR(50) NOT NULL,
  class          VARCHAR(50) NOT NULL DEFAULT 'basic',
  description    TEXT NULL,
  base_cost_metal     BIGINT NOT NULL DEFAULT 0,
  base_cost_crystal   BIGINT NOT NULL DEFAULT 0,
  base_cost_deuterium BIGINT NOT NULL DEFAULT 0,
  base_cost_energy    BIGINT NOT NULL DEFAULT 0,
  growth_factor   DOUBLE NOT NULL DEFAULT 2.0,
  base_time_seconds BIGINT NOT NULL DEFAULT 3600,
  prerequisites  JSON NULL,
  bonuses        JSON NULL,
  requirements   JSON NULL,
  created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_research_progress (
  id            CHAR(36) NOT NULL PRIMARY KEY,
  user_id       CHAR(36) NOT NULL,
  tech_id       CHAR(36) NOT NULL,
  status        ENUM('available','in_progress','completed') NOT NULL DEFAULT 'available',
  progress      INT NOT NULL DEFAULT 0,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_player_tech (user_id, tech_id),
  CONSTRAINT fk_research_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_tech FOREIGN KEY (tech_id) REFERENCES research_technologies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Expeditions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS expeditions (
  id            CHAR(36) NOT NULL PRIMARY KEY,
  user_id       CHAR(36) NOT NULL,
  name          VARCHAR(100) NOT NULL,
  type          ENUM('exploration','mining','combat','research') NOT NULL DEFAULT 'exploration',
  tier          INT NOT NULL DEFAULT 1,
  target_coords VARCHAR(32) NULL,
  status        ENUM('preparing','active','completed','failed') NOT NULL DEFAULT 'preparing',
  fleet_comp    JSON NULL,
  troop_comp    JSON NULL,
  discoveries   JSON NULL,
  casualties    JSON NULL,
  started_at    DATETIME NULL,
  completed_at  DATETIME NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_expeditions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS expedition_encounters (
  id            CHAR(36) NOT NULL PRIMARY KEY,
  expedition_id CHAR(36) NOT NULL,
  encounter_type VARCHAR(50) NOT NULL,
  description   TEXT NULL,
  rewards       JSON NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_encounters_expedition FOREIGN KEY (expedition_id) REFERENCES expeditions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Economy: market, currencies, bank
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS market_orders (
  id            CHAR(36) NOT NULL PRIMARY KEY,
  user_id       CHAR(36) NOT NULL,
  type          ENUM('buy','sell') NOT NULL,
  resource      ENUM('metal','crystal','deuterium','energy') NOT NULL,
  amount        BIGINT NOT NULL,
  price_per_unit DOUBLE NOT NULL,
  status        ENUM('active','completed','cancelled') NOT NULL DEFAULT 'active',
  filled_amount BIGINT NOT NULL DEFAULT 0,
  completed_at  DATETIME NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_market_resource (resource, status),
  CONSTRAINT fk_market_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_currency (
  id              CHAR(36) NOT NULL PRIMARY KEY,
  user_id         CHAR(36) NOT NULL UNIQUE,
  silver          BIGINT NOT NULL DEFAULT 0,
  gold            BIGINT NOT NULL DEFAULT 0,
  platinum        BIGINT NOT NULL DEFAULT 0,
  silver_earned   BIGINT NOT NULL DEFAULT 0,
  silver_spent    BIGINT NOT NULL DEFAULT 0,
  gold_earned     BIGINT NOT NULL DEFAULT 0,
  gold_spent      BIGINT NOT NULL DEFAULT 0,
  platinum_earned BIGINT NOT NULL DEFAULT 0,
  platinum_spent  BIGINT NOT NULL DEFAULT 0,
  last_updated    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_currency_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS currency_transactions (
  id            CHAR(36) NOT NULL PRIMARY KEY,
  user_id       CHAR(36) NOT NULL,
  currency_type ENUM('silver','gold','platinum') NOT NULL,
  amount        BIGINT NOT NULL,
  reason        VARCHAR(100) NULL,
  related_id    CHAR(36) NULL,
  balance_before BIGINT NOT NULL DEFAULT 0,
  balance_after  BIGINT NOT NULL DEFAULT 0,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_curtx_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bank_accounts (
  id                  CHAR(36) NOT NULL PRIMARY KEY,
  user_id             CHAR(36) NOT NULL UNIQUE,
  account_type        ENUM('standard','savings','vault') NOT NULL DEFAULT 'standard',
  account_balance     BIGINT NOT NULL DEFAULT 0,
  interest_rate       DOUBLE NOT NULL DEFAULT 0.05,
  last_interest_payment DATETIME NULL,
  total_interest_earned BIGINT NOT NULL DEFAULT 0,
  max_withdrawal      BIGINT NOT NULL DEFAULT 1000000,
  max_deposit         BIGINT NOT NULL DEFAULT 10000000,
  is_active           TINYINT(1) NOT NULL DEFAULT 1,
  created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bank_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bank_transactions (
  id               CHAR(36) NOT NULL PRIMARY KEY,
  account_id       CHAR(36) NOT NULL,
  transaction_type ENUM('deposit','withdrawal','interest','fee','transfer') NOT NULL,
  amount           BIGINT NOT NULL,
  description      VARCHAR(255) NULL,
  balance_before   BIGINT NOT NULL DEFAULT 0,
  balance_after    BIGINT NOT NULL DEFAULT 0,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_banktx_account FOREIGN KEY (account_id) REFERENCES bank_accounts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Social: alliances, messages, espionage
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alliances (
  id           CHAR(36) NOT NULL PRIMARY KEY,
  name         VARCHAR(100) NOT NULL UNIQUE,
  tag          VARCHAR(10) NOT NULL UNIQUE,
  description  TEXT NULL,
  announcement TEXT NULL,
  resources    JSON NULL,
  level        INT NOT NULL DEFAULT 1,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alliance_members (
  id          CHAR(36) NOT NULL PRIMARY KEY,
  alliance_id CHAR(36) NOT NULL,
  user_id     CHAR(36) NOT NULL,
  rank        ENUM('leader','officer','member','recruit') NOT NULL DEFAULT 'member',
  points      BIGINT NOT NULL DEFAULT 0,
  joined_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_alliance_user (alliance_id, user_id),
  CONSTRAINT fk_alm_alliance FOREIGN KEY (alliance_id) REFERENCES alliances(id) ON DELETE CASCADE,
  CONSTRAINT fk_alm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS messages (
  id              CHAR(36) NOT NULL PRIMARY KEY,
  from_user_id    CHAR(36) NULL,
  to_user_id      CHAR(36) NULL,
  from_name       VARCHAR(100) NULL,
  to_name         VARCHAR(100) NULL,
  subject         VARCHAR(255) NULL,
  body            TEXT NULL,
  type            ENUM('player','combat','espionage','system','alliance') NOT NULL DEFAULT 'system',
  is_read         TINYINT(1) NOT NULL DEFAULT 0,
  battle_report   JSON NULL,
  espionage_report JSON NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_messages_from FOREIGN KEY (from_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_messages_to FOREIGN KEY (to_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS espionage_scans (
  id          CHAR(36) NOT NULL PRIMARY KEY,
  player_id   CHAR(36) NOT NULL,
  target_id   CHAR(36) NOT NULL,
  scan_type   VARCHAR(50) NOT NULL DEFAULT 'basic',
  success     TINYINT(1) NOT NULL DEFAULT 0,
  detected    TINYINT(1) NOT NULL DEFAULT 0,
  scan_data   JSON NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_esp_player FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_esp_target FOREIGN KEY (target_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Ops / system
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS server_game_ticks (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  job_key     VARCHAR(64) NOT NULL,
  processed_count INT NOT NULL DEFAULT 0,
  started_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  duration_ms INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_settings (
  id          CHAR(36) NOT NULL PRIMARY KEY,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value JSON NULL,
  description VARCHAR(255) NULL,
  category    VARCHAR(50) NOT NULL DEFAULT 'general',
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
